services:
  - type: web
    name: rechargehub-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://hubrecharge.onrender.com